/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPushConfigRouteImport } from './routes/api.push.config'
import { Route as ApiPushDeliverRouteImport } from './routes/api.push.deliver'
import { Route as ApiPushScheduleRouteImport } from './routes/api.push.schedule'
import { Route as ApiPushTestRouteImport } from './routes/api.push.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/api/push/config',
  path: '/api/push/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushDeliverRoute = ApiPushDeliverRouteImport.update({
  id: '/api/push/deliver',
  path: '/api/push/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushScheduleRoute = ApiPushScheduleRouteImport.update({
  id: '/api/push/schedule',
  path: '/api/push/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/deliver': typeof ApiPushDeliverRoute
  '/api/push/schedule': typeof ApiPushScheduleRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/deliver': typeof ApiPushDeliverRoute
  '/api/push/schedule': typeof ApiPushScheduleRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/deliver': typeof ApiPushDeliverRoute
  '/api/push/schedule': typeof ApiPushScheduleRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/push/config'
    | '/api/push/deliver'
    | '/api/push/schedule'
    | '/api/push/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/push/config'
    | '/api/push/deliver'
    | '/api/push/schedule'
    | '/api/push/test'
  id:
    | '__root__'
    | '/'
    | '/api/push/config'
    | '/api/push/deliver'
    | '/api/push/schedule'
    | '/api/push/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPushConfigRoute: typeof ApiPushConfigRoute
  ApiPushDeliverRoute: typeof ApiPushDeliverRoute
  ApiPushScheduleRoute: typeof ApiPushScheduleRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/config': {
      id: '/api/push/config'
      path: '/api/push/config'
      fullPath: '/api/push/config'
      preLoaderRoute: typeof ApiPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/deliver': {
      id: '/api/push/deliver'
      path: '/api/push/deliver'
      fullPath: '/api/push/deliver'
      preLoaderRoute: typeof ApiPushDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/schedule': {
      id: '/api/push/schedule'
      path: '/api/push/schedule'
      fullPath: '/api/push/schedule'
      preLoaderRoute: typeof ApiPushScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPushConfigRoute: ApiPushConfigRoute,
  ApiPushDeliverRoute: ApiPushDeliverRoute,
  ApiPushScheduleRoute: ApiPushScheduleRoute,
  ApiPushTestRoute: ApiPushTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
